### ISSUE TITLE
Have you tried multi-resolution hash encoding to speed up the training time

### ISSUE THREAD

**Issue by BCL123456-BAL** [zhengyuf/PointAvatar#11]
It was a great job !
But six hours of GPU training time was still hard to accept.
Have you tried multi-resolution hash encoding to speed up the training time.
Is it because point cloud requires too high resolution of voxel grid?

**Comment by zhengyuf** [comment]
Hi,

I did give it a small try, but it didn't work very easily. I found it hard to use hash-grid encoding for the geometry and deformation MLP. 

I'm not sure why, but my feeling is that the problem is not the usage of point cloud instead of NeRF, but the reliance on the surface normals (which is the gradient of the deformed SDF). We didn't want to remove the surface normals from our formulation, because this is essential for achieving good surface geometry.

I might be wrong, and it would indeed be great if there is a way to combine this work with multi-resolution hash encoding.

Yufeng
