### ISSUE TITLE
Expression Transfer Issue

### ISSUE THREAD

**Issue by atgao** [zhengyuf/PointAvatar#17]
Hi, thank you so much for sharing the great work!

I am wondering, is it possible to do expression transfer with your avatar? If I train a model on person 1, then use the flame parameters from the preprocessing step from a different person (person 2), can I transfer the expression from person 2 to person 1? 

I was trying with your code/the given data on a model I trained on my own video, but I seem to get some weird result on the mouth region
![Screen Shot 2023-09-13 at 12 01 18 PM](https://github.com/zhengyuf/PointAvatar/assets/15146761/d13f8fa2-c4e6-4398-ba13-caba5b967f93)

**Comment by zhengyuf** [comment]
Hi,

Expression transfer should be possible. At least when the expression from person 2 is not too different from the training video of person 1, it should work.

With weird results, do you mean the white dots on the jaw? This is because the point cloud might become sparse after deformation, and therefore it reveals the white background. This is indeed a known artifact of PointAvatar and hopefully will get solved in the future!

Yufeng

**Comment by atgao** [comment]
I see. Does this mean that in both of the training videos, we should try to capture the same set of expressions?
![Screen Shot 2023-09-17 at 9 17 20 AM](https://github.com/zhengyuf/PointAvatar/assets/15146761/db44306c-edac-49c3-a3b0-8dc5e2f438e9)

With weird results, I mean when attempting the expression transfer from person 2 to person 1, the cheeks/mouth of person 1 don't match. For example in this image here I have person 1 on the left (the original frame was a neutral expression) and am trying to transfer the smile/open mouth from person 2 on the right.

**Comment by zhengyuf** [comment]
Hi, 

For expression transfer, we're taking the FLAME expression and pose parameters from frames of person 2, and trying to animate person 1 with these FLAME parameters. The frames of person 2 are not directly used.

In order for expression transfer to work, person 1's training data should have similar expressions to the target frame, so that the corresponding expression blendshapes can be learned. But even in this case, the expressions will not look exactly the same.

In your case, it seems like the training video doesn't contain a lot of 'laughing' expressions, and therefore the cheek deformation and teeth are not learned well in the image.

best,
Yufeng
