### ISSUE TITLE
 how can  I drive the expression of the model and get the animation

### ISSUE THREAD

**Issue by scnu-yyyyjx** [zhengyuf/PointAvatar#19]
Hello, I want to know: After I have generated a model with the original data set, how can I use the new data set to drive the expression of the original model and get the animation

**Comment by Arthur-Evans** [comment]
Hello，Are you still possessing the original data set? Can you send me one ? There is something wrong with the data set provided by the author and cannot be downloaded.

**Comment by zhengyuf** [comment]
1. Expression animation: You need to preprocess the new test video in the same way as training data (https://github.com/zhengyuf/IMavatar/tree/main/preprocess).  Copy the test data folder into the training folder, then set the dataset.test.sub_dir to the name of the test folder. Set load_images to False. Please let me know if you meet problems with the process. 

3. Dataset download: Is there still something wrong with the links? I'm able to download them. Please let me know if the issue persists for you.

**Comment by Arthur-Evans** [comment]
> 1. Expression animation: You need to preprocess the new test video in the same way as training data (https://github.com/zhengyuf/IMavatar/tree/main/preprocess).  Copy the test data folder into the training folder, then set the dataset.test.sub_dir to the name of the test folder. Set load_images to False. Please let me know if you meet problems with the process.
> 2. Dataset download: Is there still something wrong with the links? I'm able to download them. Please let me know if the issue persists for you.

Hi, I have the same problem. But I didn't understand your reply. I have two questions:
1. if I have a series of frame images captured from a video, where do I put it in the code? And does it need to be preprocessed? Because there are not only images in the training dataset, but also masks and flame_params.json and so on. But there is no preprocessing code in all the code.
2. which instruction should I run to drive the corresponding model from my own video image to generate the corresponding video image

I would appreciate if you could reply me!
From undergraduate student: Arthur

**Comment by scnu-yyyyjx** [comment]
> 1. Expression animation: You need to preprocess the new test video in the same way as training data (https://github.com/zhengyuf/IMavatar/tree/main/preprocess).  Copy the test data folder into the training folder, then set the dataset.test.sub_dir to the name of the test folder. Set load_images to False. Please let me know if you meet problems with the process.
> 
>     2. Dataset download: Is there still something wrong with the links? I'm able to download them. Please let me know if the issue persists for you.

Thank you for your reply, and I wish you success in your work.
