### ISSUE TITLE
FLAME canonical space

### ISSUE THREAD

**Issue by Zvyozdo4ka** [zhengyuf/PointAvatar#25]
1. May I ask about definition of FLAME canonical space x_0. Where can I find the definition? I did not find the definition in the paper of Flame too.

2. Why, at first, point cloud looks so deformed in canonical space a, n_c? What is canonical space a, n_c? While the point cloud with recognizable face and proportions are called as Deformed space a, n_d?
3. 
![image](https://github.com/zhengyuf/PointAvatar/assets/74532816/77d2c8b9-1c14-4d51-85c7-ae78f6da9be1)

4. Could you give a hint how to get FLAME model for considered person? You keep flame_params.json, what kind of parameters do you keep there? Can i make up flame model from this file?

**Comment by zhengyuf** [comment]
Hi,

1.  The FLAME canonical model x_o is defined to be the model of the subject with an average facial expression and an open-mouth pose.
2. The x_c space is where we learn the point cloud. We jointly learn canonical offsets with the point cloud, so that after adding the canonical offsets, the point cloud transforms into the FLAME canonical space, which is meaningful. The x_c space doesn't have a meaning by itself. Canonical v.s. deformed refers to whether frame-specific expression deformations are added.
3. Yes you can. flame_params.json contains the FLAME expression, pose and identity parameters, which are everything you need to obtain the flame model.

**Comment by Zvyozdo4ka** [comment]
Hello, @zhengyuf 

Could you give a hint how to obtain flame from this file `flame_params.json`?
